config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "/about" => "homes#about", as: "about"
  #user関連
  resources :users, only:[:show,:edit,:update] do
    resource :relationships, only:[:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :targets, only:[:new,:create,:show,:edit,:update,:index] do
    resources :target_comments, only:[:create,:destroy]
    resource :favorites, only:[:create,:destroy]
  end

  #打刻画面
  get "time_stamps" => "time_stamps#time_stamps", as: "time_stamps"
  #打刻開始
  post "time_stamps" => "time_stamps#start_stamp", as: "start_stamp"
  #打刻終了
  patch "time_stamps/:id" => "time_stamps#end_stamp", as: "end_stamp"
  #打刻一覧画面
  get "stamplists" => "time_stamps#stamp_lists", as: "stamp_lists"
  get "stamplists/:id" => "time_stamps#show", as: "stamp_list"
  patch "stamplists/:id" => "time_stamps#update"
  #打刻詳細画面とデータ更新
end

app/models/target_comment.rb
class TargetComment < ApplicationRecord
  belongs_to :user
  belongs_to :target

  validates :comment, presence: true
end

app/controllers/target_comments_controller.rb
class TargetCommentsController < ApplicationController
  before_action :set_target
  def create
    target = Target.find(params[:target_id])
    @comment = TargetComment.new(target_comment_paraams)
    @comment.user_id = current_user.id
    @comment.target_id = target.id
    @comment.save
  end

  def destroy
    @comment = TargetComment.find_by(id: params[:id], target_id: params[:target_id])
    @comment.destroy
  end

  private

  def target_comment_paraams
    params.require(:target_comment).permit(:comment)
  end

  def set_target
    @target = Target.find(params[:target_id])
  end
end

app/helpers/target_comments_helper.rb
module TargetCommentsHelper
end

app/views/target_comments/_comment_form.html.erb
<div>
  <%= form_with(model: [target, comment], local: false) do |f| %>
    <div class = "mb-3">
      <%= f.text_area :comment, rows: '5', placeholder: "コメントしてあげましょう", class: "form-control" %>
    </div>
    <div class = "mb-3">
      <%= f.submit "送信する", class: "btn btn-secondary btn-sm"%>
    </div>
  <% end %>
</div>

app/views/target_comments/_comment_index.html.erb
<% target.target_comments.each do |comment| %>
  <div class = "row border-bottom mb-2">
    <div class = "col-3 text-center mb-2">
      <%= link_to user_path(comment.user) do %>
        <%= image_tag comment.user.get_icon, size: "50x50", class: "mt-3 rounded-circle" %><br />
        <%= comment.user.name %><br />
      <% end %>
      <%= comment.created_at.strftime("%Y年%m月%d日") %>
    </div>
    <div class = "col-7 border rounded mb-2">
      <%= comment.comment %>
    </div>
    <div class = "col-2 align-self-end mb-2">
      <% if comment.user == current_user %>
        <%= link_to target_target_comment_path(comment.target, comment), method: :delete, remote: true do %>
          <button type = "button" class = "btn btn-danger btn-sm">削除</button>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/target_comments/create.js.erb
$(".form-control").val("")
$(".target-comment-index").html("<%= j(render "target_comments/comment_index", target: @target) %>")

app/views/target_comments/destroy.js.erb
$(".target-comment-index").html("<%= j(render "target_comments/comment_index", target: @target) %>")