config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "/about" => "homes#about", as: "about"
  #user関連
  resources :users, only:[:show,:edit,:update] do
    resource :relationships, only:[:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :targets, only:[:new,:create,:show,:edit,:update,:index] do
    resources :target_comments, only:[:create,:destroy]
    resource :favorites, only:[:create,:destroy]
  end

  #打刻画面
  get "time_stamps" => "time_stamps#time_stamps", as: "time_stamps"
  #打刻開始
  post "time_stamps" => "time_stamps#start_stamp", as: "start_stamp"
  #打刻終了
  patch "time_stamps/:id" => "time_stamps#end_stamp", as: "end_stamp"
  #打刻一覧画面
  get "stamplists" => "time_stamps#stamp_lists", as: "stamp_lists"
  get "stamplists/:id" => "time_stamps#show", as: "stamp_list"
  patch "stamplists/:id" => "time_stamps#update"
  #打刻詳細画面とデータ更新
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  #フォローする時
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  #フォローを外す時
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  #自分をフォローしているUser一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
  #自分がフォローしているUser一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_user.following?(user)%>
  <%= link_to user_relationships_path(user.id), method: :delete do %>
    <button type="button" class="btn btn-outline-warning btn-sm">フォロー解除</button>
  <% end %>
<% else %>
  <%= link_to user_relationships_path(user.id), method: :post do %>
    <button type="button" class="btn btn-warning btn-sm">フォロー</button>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<% if @users.exists? %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col"><!--Userの写真--></th>
          <th scope="col">名前</th><!--Userの名前-->
          <th scope="col">フォロー数</th><!--Userのフォロー数-->
          <th scope="col">フォロワー数</th><!--Userのフォロワー数-->
          <th scope="col"><!--フォローするボタン--></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(user) do %>
                <%= image_tag user.get_icon, size: "50x50", class: "mt-3 rounded-circle" %>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= user.followings.count %></td>
            <td><%= user.followers.count %></td>
            <td><%= render "relationships/btn" , user: user %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
<% else %>
  一覧はありません
<% end %>

app/views/relationships/followings.html.erb
<% if @users.exists? %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col"><!--Userの写真--></th>
          <th scope="col">名前</th><!--Userの名前-->
          <th scope="col">フォロー数</th><!--Userのフォロー数-->
          <th scope="col">フォロワー数</th><!--Userのフォロワー数-->
          <th scope="col"><!--フォローするボタン--></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(user) do %>
                <%= image_tag user.get_icon, size: "50x50", class: "mt-3 rounded-circle" %>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= user.followings.count %></td>
            <td><%= user.followers.count %></td>
            <td><%= render "relationships/btn" , user: user %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
<% else %>
  一覧はありません
<% end %>