config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "/about" => "homes#about", as: "about"
  #user関連
  resources :users, only:[:show,:edit,:update] do
    resource :relationships, only:[:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :targets, only:[:new,:create,:show,:edit,:update,:index] do
    resources :target_comments, only:[:create,:destroy]
    resource :favorites, only:[:create,:destroy]
  end

  #打刻画面
  get "time_stamps" => "time_stamps#time_stamps", as: "time_stamps"
  #打刻開始
  post "time_stamps" => "time_stamps#start_stamp", as: "start_stamp"
  #打刻終了
  patch "time_stamps/:id" => "time_stamps#end_stamp", as: "end_stamp"
  #打刻一覧画面
  get "stamplists" => "time_stamps#stamp_lists", as: "stamp_lists"
  get "stamplists/:id" => "time_stamps#show", as: "stamp_list"
  patch "stamplists/:id" => "time_stamps#update"
  #打刻詳細画面とデータ更新
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  #自分がフォローする側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  #自分がフォローした人の一覧をフォローされた人(followed)を参照して出力
  has_many :followings, through: :relationships, source: :followed

  #自分がフォローされる側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  #自分をフォローしている人の一覧をフォローした人(follower)を参照して出力
  has_many :followers, through: :reverse_of_relationships,source: :follower

  has_many :targets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :target_comments, dependent: :destroy
  has_many :time_stamps, dependent: :destroy

  validates :name, presence: true, length: {minimum: 2, maximum: 15}
  validates :introduction, length: {maximum: 50}

  has_one_attached :profile_image

  #画像を取得する処理
  def get_icon
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  #フォローする際の処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  #フォローを外す際の処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  #フォローしているかの判別
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @targets = Target.where(user_id: @user)
    # @targets = Target.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "更新が成功しました"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<table class = "table">
  <tr>
    <th class = "d-flex justify-content-center">
      <%= image_tag user.get_icon, size: "100x100", class: "mt-3 rounded-circle" %>
    </th>
  </tr>
  <tr>
    <th>名前</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>紹介</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>Follow数</th>
    <th>
      <%= link_to user_followings_path(user) do %>
        <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>Follower数</th>
    <th>
      <%= link_to user_followers_path(user) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
  <tr>
  <% if current_user != user  %>
    <th>
      <%= render "relationships/btn", user: user %>
      <%= link_to user_path(user) do %>
        <button type = "button" class = "btn btn-light">この人の目標一覧を見る</button>
      <% end %>
    </th>
  <% else %>
    <th>
      <%= link_to edit_user_path(user) do %>
        <button type = "button" class = "btn btn-secondary btn-lg">編集</button>
      <% end %>
    </th>
    <th>
      <%= link_to new_target_path do %>
        <button type = "button" class = "btn btn-warning btn-lg">目標を追加する</button>
      <% end %>
    </th>
  <% end %>
  </tr>
</table>

app/views/users/edit.html.erb
<div class = "container py-5">
  <%= render "layouts/error", obj: @user %>
  <div class = "row d-flex justify-content-center">
    <div class = "col-5">
      <h3>情報編集</h3>
        <%= form_with model: @user, url: user_path(@user), method: :patch, local: true do |f| %>
          <div class = "mb-3">
            <%= f.label :profile_image, "プロフィール画像", class: "form-label" %><br />
            <%= f.file_field :profile_image, class: "form-control text-center"%>
          </div>
          <div class = "mb-3">
            <%= f.label :name, "名前", class: "form-label"%><br />
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class = "mb-3">
            <%= f.label :introduction, "説明",class: "form-label"%><br />
            <%= f.text_field :introduction, class: "form-control" %>
          </div>
          <div class = "mb-3">
            <%= f.submit "変更する" , class: "btn btn-warning"%>
            <%= link_to :back do %>
              <button type = "button" class = "btn btn-secondary">戻る</button>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h2>User詳細画面</h2>
<div class = "container">
  <div class = "row">
    <div class = "col-4">
      <!--userのプロフィール詳細-->
      <%= render "info", user: @user %>
    </div>
    <div class = "col-8">
      <!--上のuserの目標一覧-->
      <%= render "targets/index", targets: @targets %>
    </div>
  </div>
</div>