config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "/about" => "homes#about", as: "about"
  #user関連
  resources :users, only:[:show,:edit,:update] do
    resource :relationships, only:[:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :targets, only:[:new,:create,:show,:edit,:update,:index] do
    resources :target_comments, only:[:create,:destroy]
    resource :favorites, only:[:create,:destroy]
  end

  #打刻画面
  get "time_stamps" => "time_stamps#time_stamps", as: "time_stamps"
  #打刻開始
  post "time_stamps" => "time_stamps#start_stamp", as: "start_stamp"
  #打刻終了
  patch "time_stamps/:id" => "time_stamps#end_stamp", as: "end_stamp"
  #打刻一覧画面
  get "stamplists" => "time_stamps#stamp_lists", as: "stamp_lists"
  get "stamplists/:id" => "time_stamps#show", as: "stamp_list"
  patch "stamplists/:id" => "time_stamps#update"
  #打刻詳細画面とデータ更新
end

app/models/time_stamp.rb
class TimeStamp < ApplicationRecord

  belongs_to :user

  #1日1回の打刻のため、target_id,dateが同じものは重複しないバリデーション
  validates :user_id, uniqueness: { scope: :date }

  #1日の合計を出すメソッド
  def day_total_time
    if end_time.present?
      (end_time-start_time)/3600.to_i
    else
      total_time = 0.to_i
    end
  end

  def self.stamp_list(day)
    self.find_by(date: day)
  end

  def time_update

  end
end

app/controllers/time_stamps_controller.rb
class TimeStampsController < ApplicationController

  def time_stamps
    @stamp = TimeStamp.find_by(end_time: nil, user_id: current_user.id)
    @date = Date.current
  end

  def start_stamp
    start_time = TimeStamp.new(date: Date.current, start_time: Time.current, end_time: nil, user_id: current_user.id)
    if start_time.save
      redirect_to time_stamps_path, notice: "打刻を開始しました"
    else
      render :time_stamps
    end
  end

  def end_stamp
    stamp = TimeStamp.find(params[:id])
    stamp.update(end_time: Time.current)# binding.pry
    redirect_to time_stamps_path, notice: "打刻を終了しました"
  end

  def stamp_lists
    params[:month] = Date.current.strftime('%Y%m%d') unless params[:month]
    @month = (0..31).to_a.map{ |i| (Date.parse(params[:month]).beginning_of_month+i) if Date.parse(params[:month]).end_of_month.strftime('%d').to_i > i}.compact
    #@stamp_list = TimeStamp.where(user_id: current_user)
    @date = Date.parse(params[:month])
  end

  def show
    @stamp = TimeStamp.find(params[:id])
  end

  def update
    @stamp = TimeStamp.find(params[:id])
    #パラメータをstart_timeの各日付と時間(1i~5i)に割り当て
    # @stamp.start_time = Time.new(params[:time_stamp]['start_time(1i)'].to_i, params[:time_stamp]['start_time(2i)'].to_i, params[:time_stamp]['start_time(3i)'].to_i, params[:time_stamp]['start_time(4i)'].to_i, params[:time_stamp]['start_time(5i)'].to_i)
    #パラメータをend_timeの各日付と時間(1i~5i)に割り当て
    # @stamp.end_time = Time.new(params[:time_stamp]['end_time(1i)'].to_i, params[:time_stamp]['end_time(2i)'].to_i, params[:time_stamp]['end_time(3i)'].to_i, params[:time_stamp]['end_time(4i)'].to_i, params[:time_stamp]['end_time(5i)'].to_i)
    
    if @stamp.update
      #binding.pry
      redirect_to stamp_list_path, notice: "正常に更新しました"
    else
      render :show
    end
  end
end

app/helpers/time_stamps_helper.rb
module TimeStampsHelper
end

app/views/time_stamps/index.html.erb
<div>
  <% @times.each do |target| %>

  <% end %>
</div>

app/views/time_stamps/show.html.erb
<div class = "container py-5">
  <%= link_to "打刻一覧画面に戻る", stamp_lists_path, class: "text-secondary" %>
  <div class = "row d-flex justify-content-center">
    <div class = "col-4">
      <div class = "card">
        <h3 class = "card-header">
          日付<strong><%= @stamp.date.strftime("%m月 %d日") %></strong>
        </h3>
        <div class = "card-body">
          <h3 class = "card-text">
            開始時間:<strong><%= @stamp.start_time.strftime("%H:%M") %></strong>
          </h3>
          <h3 class = "card-text">
            <% if @stamp.end_time.nil? %>
              終了時間: -
            <% else %>
              終了時間:<strong><%= @stamp.end_time.strftime("%H:%M") %></strong>
            <% end %>
          </h3>
        </div>
      </div>
    </div>
    <div class = "col-4">
      <div class = "card">
        <h3 class = "card-header">
          修正
        </h3>
        <div class = "card-body">
          <%= form_with model: @stamp, url: stamp_list_path(@stamp), method: :patch, local: true do |f| %>
            <h3 class = "mb-3">
              <%= f.label :start_time, "開始時間" %>
              <%= f.text_field :start_time, class: "form-controll" %>
            </h3>
            <h3 class = "mb-3">
              <%= f.label :end_time, "開始時間" %>
              <%= f.text_field :end_time, class: "form-controll" %>
            </h3>
            <%= f.submit "変更", class: "btn btn-sm btn-warning" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/time_stamps/stamp_list.html.erb
<div class = "container py-5">
  <div class = "row">
    <div class = "col-4">
      <h3>総時間(月)<%= %></h3>
    </div>
    <div class = "col-6 d-flex justify-content-center">
      <%= link_to action: "stamp_list", month: @date.last_month do %>
        <i class="fas fa-angle-left fa-2x text-secondary"></i>
      <% end %>
      <h3><%= "#{@date.year}年#{@date.month}月" %></h3>
      <%= link_to action: "stamp_list", month: @date.next_month do %>
        <i class="fas fa-angle-right fa-2x text-secondary"></i>
      <% end %>
    </div>
  </div>
  <div class = "row">
    <table class = "table table-bordered text-center">
      <thead class = "thead-dark">
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>打刻開始時間</th>
          <th>打刻終了時間</th>
          <th>総時間(日)</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @month.each do |day| %>
        <% list = current_user.time_stamps.stamp_list(day) %>
          <tr>
            <td><%= day.strftime("%m/%d") %></td>
            <td><%= day.strftime("%a") %></td>
            <td><%= list.start_time.strftime("%H:%M") if list.present? %></td>
              <td><%= list.end_time.strftime("%H:%M") if list.present? && list.end_time.present?%></td>
            <td><%= list.day_total_time.round(2) if list.present? %></td>
            <td>
              <% if list.present? %>
                <%= link_to "詳細", time_stamp_path(list.id), class: "btn btn-sm btn-warning" %>
              <% end %>
            </td>
          </tr>
         <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/time_stamps/stamp_lists.html.erb
<div class = "container py-5">
  <div class = "row">
    <div class = "col-4">
      <h3>総時間(月)<%= %></h3>
    </div>
    <div class = "col-6 d-flex justify-content-center">
      <%= link_to action: "stamp_lists", month: @date.last_month do %>
        <i class="fas fa-angle-left fa-2x text-secondary"></i>
      <% end %>
      <h3><%= "#{@date.year}年#{@date.month}月" %></h3>
      <%= link_to action: "stamp_lists", month: @date.next_month do %>
        <i class="fas fa-angle-right fa-2x text-secondary"></i>
      <% end %>
    </div>
  </div>
  <div class = "row">
    <table class = "table table-bordered text-center">
      <thead class = "thead-dark">
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>打刻開始時間</th>
          <th>打刻終了時間</th>
          <th>総時間(日)</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @month.each do |day| %>
        <% list = current_user.time_stamps.stamp_list(day) %>
          <tr>
            <td><%= day.strftime("%m/%d") %></td>
            <td><%= day.strftime("%a") %></td>
            <td><%= list.start_time.strftime("%H:%M") if list.present? %></td>
              <td><%= list.end_time.strftime("%H:%M") if list.present? && list.end_time.present?%></td>
            <td><%= list.day_total_time.round(2) if list.present? %></td>
            <td>
              <% if list.present? %>
                <%= link_to "詳細", stamp_list_path(list.id), class: "btn btn-sm btn-warning" %>
              <% end %>
            </td>
          </tr>
         <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/time_stamps/time_stamps.html.erb
<div class = "container py-5">
  <div class = "row justify-content-between">
    <div class = "col-3">
      <h3>打刻画面</h3>
    </div>
    <div class = "col-3">
      <%= link_to stamp_lists_path, class: "text-secondary" do %>
        <h3>打刻時間一覧へ</h3>
      <% end %>
    </div>
  </div>

  <div class = "row">
    <div class = "col-6">
      <div class = "card">
        <div class = "card-header bg-warning ">
          <h3 class = "text-white text-center"><%= @date.month %>月<%= @date.day %>日</h3>
        </div>
        <div class = "card-body py-2">
          <h3>
            <p id = "realtime" class = "text-center text-center"></p>
          </h3>
        </div>
      </div>
    </div>

    <div class = "col-4">
      <div class = "mb-3">
        <%= button_to "開始", start_stamp_path, class: "btn btn-lg btn-success m-2" %>
        <% if @stamp.present? %>
          <%= button_to "終了", end_stamp_path(@stamp), class: "btn btn-lg btn-warning m-2", method: :patch %>
        <% else %>
          <button type = "btn" class = "btn btn-lg btn-warning m-2" disabled >終了</button>
        <% end %>
      </div>
    </div>
  </div>
  <p class = "text-danger">注意: 打刻は1日1回しか出来ません。もし、ミスをしたら打刻一覧の詳細ボタンから変更をお願いします。</p>
</div>